<a href="https://colab.research.google.com/github/lenaphamthi/bai_tap_numpy/blob/main/bai_tap_numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

bai 1

In [ ]:
import numpy as np

In [ ]:
#Ma trận 
A = np.random.random([7,5])
A

array([[0.91290158, 0.49608396, 0.43193466, 0.43799641, 0.3958345 ],
       [0.75069806, 0.81562863, 0.04830302, 0.76036131, 0.66928988],
       [0.02604011, 0.55900739, 0.52784377, 0.27628276, 0.81279372],
       [0.96492676, 0.1256832 , 0.0853334 , 0.76931734, 0.3733767 ],
       [0.2130325 , 0.27114398, 0.07151961, 0.16257487, 0.54072259],
       [0.90349619, 0.54040348, 0.82025163, 0.38902345, 0.51831289],
       [0.12045568, 0.99413112, 0.31129592, 0.72234863, 0.82059454]])

bai 2

In [ ]:
#Ma trận không 
np.zeros([6,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

bai 3

In [ ]:
#Ma trận vuông 
np.random.randint(1,20,[7,7])

array([[ 7, 12,  6,  5,  4,  4,  8],
       [18, 19, 18,  6, 14,  5,  9],
       [14, 14, 12,  5,  7,  3, 15],
       [ 5, 17,  2, 11, 12,  7,  9],
       [19, 17,  8, 10,  6, 15, 12],
       [12,  3,  4, 13,  6, 16,  8],
       [ 2,  1, 16, 19,  6,  5,  4]])

bai 4

In [ ]:
#Ma trận chéo
a = np.zeros([6,6])
np.fill_diagonal(a,val=15)
a

array([[15.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 15.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 15.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 15.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 15.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 15.]])

bai 5

In [ ]:
#Ma trận tam giác trên
a = np.random.randint(1,10,[8,8])
np.triu(a,k=0)



array([[9, 3, 2, 8, 2, 4, 1, 1],
       [0, 8, 8, 5, 4, 4, 7, 5],
       [0, 0, 7, 7, 5, 8, 1, 7],
       [0, 0, 0, 5, 9, 3, 9, 3],
       [0, 0, 0, 0, 8, 9, 1, 5],
       [0, 0, 0, 0, 0, 8, 9, 4],
       [0, 0, 0, 0, 0, 0, 5, 4],
       [0, 0, 0, 0, 0, 0, 0, 2]])

bai 6 

In [ ]:
#Ma trận tam giác dưới 
b = np.random.randint(1,10,[8,8])
np.tril(b,k=0)

array([[4, 0, 0, 0, 0, 0, 0, 0],
       [1, 8, 0, 0, 0, 0, 0, 0],
       [1, 4, 3, 0, 0, 0, 0, 0],
       [6, 4, 7, 1, 0, 0, 0, 0],
       [9, 8, 6, 2, 7, 0, 0, 0],
       [4, 2, 6, 1, 9, 7, 0, 0],
       [8, 8, 1, 9, 8, 5, 8, 0],
       [8, 7, 5, 2, 7, 3, 7, 3]])

bai 7

In [ ]:
#Ma tran don vi
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

bai 8

In [ ]:
#Cộng 2 ma trận 
A = np.random.randint(1,10,[6,7])
B = np.random.randint(1,10,[6,7])
print("A+B:",A+B)

A+B: [[10 13 15 14  5 10 10]
 [14 10 13 10  8 12 10]
 [ 7  8  8  9  7  7 12]
 [15 17 10 14  7  8  6]
 [14 11 12  6  9 13  9]
 [ 6 11 11  8 11  7 12]]


In [ ]:
#Nhân vô hướng một số với ma trận 
a = np.random.randint(1,5,[5,8])
print(a)
m = int(input("nhap 1 so nguyen: "))
print("Nhan vo huong: ",a*m)

[[3 4 3 4 3 1 3 1]
 [1 1 3 1 4 1 3 2]
 [4 1 1 1 4 2 4 2]
 [1 3 1 4 4 2 2 3]
 [2 1 1 2 3 4 3 4]]
nhap 1 so nguyen: 1
Nhan vo huong:  [[3 4 3 4 3 1 3 1]
 [1 1 3 1 4 1 3 2]
 [4 1 1 1 4 2 4 2]
 [1 3 1 4 4 2 2 3]
 [2 1 1 2 3 4 3 4]]


In [ ]:
#Chuyển vị ma trận 
b = np.random.randint(1,10,[3,7])
print(b)
print("Chuyển vị: ",b.T)

[[5 5 9 6 4 8 8]
 [6 9 5 2 5 2 3]
 [2 8 7 2 1 1 3]]
Chuyển vị:  [[5 6 2]
 [5 9 8]
 [9 5 7]
 [6 2 2]
 [4 5 1]
 [8 2 1]
 [8 3 3]]


In [ ]:
#Nhân 2 ma trận
A = np.random.randint(1,5,[5,7])
print("ma tran A: ", A)
B = np.random.randint(1,5,[7,3])
print("ma tran B: ", B)
print("Nhan 2 ma tran A va B: ",A.dot(B))


ma tran A:  [[2 4 1 1 4 3 3]
 [4 4 3 3 2 3 1]
 [1 1 3 4 3 2 1]
 [3 4 4 3 1 1 2]
 [3 3 3 3 1 3 3]]
ma tran B:  [[4 4 4]
 [3 2 3]
 [2 4 2]
 [4 2 1]
 [2 2 1]
 [3 3 1]
 [4 4 3]]
Nhan 2 ma tran A va B:  [[55 51 39]
 [63 59 45]
 [45 42 25]
 [57 55 43]
 [62 59 43]]


In [ ]:
#Ma trận khả nghịch 
A = np.random.randint(1,5,[])

In [ ]:
c = np.random.randint(1,5,[5,7])
c_i = np.linalg.pinv(c)
print(c @ c_i)

[[ 1.00000000e+00  4.44089210e-16  4.44089210e-16  1.11022302e-16
  -1.66533454e-16]
 [ 6.10622664e-16  1.00000000e+00  9.99200722e-16  5.55111512e-17
  -5.55111512e-17]
 [ 4.44089210e-16  4.44089210e-16  1.00000000e+00 -5.55111512e-16
   1.94289029e-16]
 [-5.55111512e-17  6.66133815e-16  2.77555756e-16  1.00000000e+00
  -2.77555756e-16]
 [-5.55111512e-17  2.22044605e-16  5.55111512e-16  1.66533454e-16
   1.00000000e+00]]


bai 9

In [ ]:
#vector hang
y = np.array([[1],
              [2],
              [3],
              [4],
              [5],
               [6],
               [7],
               [8]])
y.T.shape

(1, 8)

In [ ]:
#vector cot
y = np.array([[1],
              [2],
              [3],
              [4],
              [5],
               [6],
               [7],
               [8]])
y.shape

(8, 1)

bai 10

In [14]:
import numpy as np
A = np.random.randint(-10,10,[3,3])
y = np.random.randint(1,5)
A_inv = np.linalg.pinv(A)
x = np.dot(A_inv, y)
print(x)

[[ 0.140625 -0.671875  1.40625 ]
 [-0.546875  0.390625 -1.46875 ]
 [ 0.109375 -0.078125  1.09375 ]]


In [8]:
import numpy as np
a = np.random.randint(1,20,[3,2])
a.ndim


2