<a href="https://colab.research.google.com/github/lenaphamthi/bai_tap_numpy/blob/main/bai_tap_numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm này.



numpy. apply_along_axis ( func1d , axis , arr , * args , ** kwargs )
+ hàm func1d (M,) -> (Nj…) : Hàm này phải chấp nhận mảng 1-D. Nó được áp dụng cho các lát arr 1-D dọc theo trục được chỉ định.
+ axis : số nguyên trục

Trục dọc theo arr được cắt.

+ arr :ndarray (Ni…, M, Nk…)

Đầu vào mảng.

+ args: bất kỳ

Đối số bổ sung cho func1d .

+ kwargs: bất kỳ

câu 2 : Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [ ]:
import numpy as np
a = np.random.randint(1,10,[15,17])
a

array([[8, 5, 4, 9, 7, 7, 1, 8, 1, 5, 3, 6, 6, 4, 2, 9, 1],
       [9, 3, 9, 5, 6, 5, 2, 1, 2, 5, 8, 6, 5, 4, 9, 1, 7],
       [4, 3, 2, 6, 5, 4, 1, 2, 6, 9, 2, 4, 7, 1, 7, 6, 5],
       [7, 5, 1, 4, 6, 3, 5, 6, 2, 1, 6, 4, 9, 5, 4, 1, 2],
       [9, 1, 7, 1, 9, 6, 7, 3, 1, 4, 7, 2, 2, 2, 5, 2, 1],
       [9, 1, 1, 5, 6, 7, 7, 1, 2, 4, 2, 7, 1, 5, 9, 3, 9],
       [5, 6, 6, 3, 5, 3, 3, 3, 2, 7, 6, 9, 7, 9, 4, 8, 1],
       [2, 1, 1, 9, 3, 6, 8, 5, 7, 5, 2, 9, 5, 6, 6, 6, 6],
       [6, 4, 6, 4, 5, 2, 2, 3, 1, 9, 4, 1, 2, 1, 4, 2, 8],
       [3, 2, 1, 4, 7, 1, 8, 6, 9, 6, 5, 1, 6, 8, 6, 6, 3],
       [5, 4, 8, 7, 6, 7, 7, 5, 7, 5, 1, 1, 6, 7, 4, 5, 6],
       [7, 8, 9, 9, 2, 2, 6, 7, 8, 8, 2, 9, 3, 2, 9, 4, 6],
       [3, 4, 4, 6, 4, 5, 6, 4, 4, 1, 7, 3, 3, 6, 2, 2, 5],
       [4, 2, 3, 2, 9, 2, 6, 6, 3, 8, 6, 6, 6, 7, 5, 6, 2],
       [8, 1, 9, 7, 9, 1, 9, 2, 2, 6, 7, 1, 1, 9, 4, 2, 8]])

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tim_gia_tri_lon_nhat(a):
 return np.max(a)
np.apply_along_axis(tim_gia_tri_lon_nhat,1,a)

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 9, 7, 9, 9])

Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tim_gia_tri_nho_nhat(a):
  return np.min(a)
np.apply_along_axis(tim_gia_tri_nho_nhat,0,a)

array([2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1])

Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tinh_tong(a):
  return np.sum(a)
np.apply_along_axis(tinh_tong,1,a)

array([ 86,  87,  74,  71,  69,  79,  87,  87,  64,  82,  91, 101,  69,
        83,  86])