<a href="https://colab.research.google.com/github/lenaphamthi/bai_tap_numpy/blob/main/bai_tap_numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

bai 1 

In [ ]:
import numpy as np
a =np.arange(1,8)
print(a)
print("so chieu cua vector a: ",a.ndim)
print("so chieu cua vector chuyen vi vector a: ",a.T.ndim)
print("kich thuoc cua vector a: ",a.shape)
print("kich thuoc cua vector a chuyen vivector a: ",a.T.shape)

[1 2 3 4 5 6 7]
so chieu cua vector a:  1
so chieu cua vector chuyen vi vector a:  1
kich thuoc cua vector a:  (7,)
kich thuoc cua vector a chuyen vivector a:  (7,)


In [ ]:
b=np.linspace(0,6,7)
print(b)
print("so chieu cua vector b: ",b.ndim)
print("so chieu cua vector chuyen vi vector b: ",b.T.ndim)
print("kich thuoc cua vector b : ",b.shape)
print("kich thuoc cua vector chuyen vi vector b: ",b.T.shape)

[0. 1. 2. 3. 4. 5. 6.]
so chieu cua vector b:  1
so chieu cua vector chuyen vi vector b:  1
kich thuoc cua vector b :  (7,)
kich thuoc cua vector chuyen vi vector b:  (7,)


In [ ]:
c=np.logspace(1,7,7)
print(c)
print("so chieu cua vector c: ",c.ndim)
print("so chieu cua vector vector chuyen vi vector c: ",c.T.ndim)
print("kich thuoc cua vector c: ",c.shape)
print("kich thuoc cua vector chuyen vi vector c: ",c.T.shape)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07]
so chieu cua vector c:  1
so chieu cua vector vector chuyen vi vector c:  1
kich thuoc cua vector c:  (7,)
kich thuoc cua vector chuyen vi vector c:  (7,)


In [ ]:
d=np.random.rand(7)
print(d)
print("so chieu cua vector d: ",d.ndim)
print("so chieu cua vector chuyen vi vector d: ",d.T.ndim)
print("kich thuoc cua vector d: ",d.shape)
print("kich thuoc cua vector chuyen vi vector d: ",d.T.shape)

[0.52101617 0.80052201 0.19406416 0.00399553 0.76087948 0.27395173
 0.58599998]
so chieu cua vector d:  1
so chieu cua vector chuyen vi vector d:  1
kich thuoc cua vector d:  (7,)
kich thuoc cua vector chuyen vi vector d:  (7,)


bai 2

In [9]:
#ham arange()
import numpy as np
a = np.arange(1,71).reshape(10,7)
print(a)
print("so chieu cua ma tran A: ",a.ndim)
print("so chieu cua ma tran chuyen vi A: ",a.T.ndim)
print("so kich thuoc cua ma tran A: ",a.shape)
print("so kich thuoc cua ma tran chuyen vi A: ",a.T.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70]]
so chieu cua ma tran A:  2
so chieu cua ma tran chuyen vi A:  2
so kich thuoc cua ma tran A:  (10, 7)
so kich thuoc cua ma tran chuyen vi A:  (7, 10)


In [19]:
#ham linspace()
a = np.linspace(0,70,num=70).reshape(10,7)
print(a)
print("so chieu cua ma tran A: ",a.ndim)
print("so chieu cua ma tran chuyen vi A: ",a.T.ndim)
print("so kich thuoc cua ma tran A: ",a.shape)
print("so kich thuoc cua ma tran chuyen vi A: ",a.T.shape)


[[ 0.          1.01449275  2.02898551  3.04347826  4.05797101  5.07246377
   6.08695652]
 [ 7.10144928  8.11594203  9.13043478 10.14492754 11.15942029 12.17391304
  13.1884058 ]
 [14.20289855 15.2173913  16.23188406 17.24637681 18.26086957 19.27536232
  20.28985507]
 [21.30434783 22.31884058 23.33333333 24.34782609 25.36231884 26.37681159
  27.39130435]
 [28.4057971  29.42028986 30.43478261 31.44927536 32.46376812 33.47826087
  34.49275362]
 [35.50724638 36.52173913 37.53623188 38.55072464 39.56521739 40.57971014
  41.5942029 ]
 [42.60869565 43.62318841 44.63768116 45.65217391 46.66666667 47.68115942
  48.69565217]
 [49.71014493 50.72463768 51.73913043 52.75362319 53.76811594 54.7826087
  55.79710145]
 [56.8115942  57.82608696 58.84057971 59.85507246 60.86956522 61.88405797
  62.89855072]
 [63.91304348 64.92753623 65.94202899 66.95652174 67.97101449 68.98550725
  70.        ]]
so chieu cua ma tran A:  2
so chieu cua ma tran chuyen vi A:  2
so kich thuoc cua ma tran A:  (10, 7)
so kich 

In [21]:
#hamlogspace()
a = np.logspace(0,70,num=70).reshape(10,7)
print(a)
print("so chieu cua ma tran A: ",a.ndim)
print("so chieu cua ma tran chuyen vi A: ",a.T.ndim)
print("so kich thuoc cua ma tran A: ",a.shape)
print("so kich thuoc cua ma tran chuyen vi A: ",a.T.shape)

[[1.00000000e+00 1.03393385e+01 1.06901920e+02 1.10529514e+03
  1.14280206e+04 1.18158173e+05 1.22167735e+06]
 [1.26313356e+07 1.30599655e+08 1.35031404e+09 1.39613539e+10
  1.44351164e+11 1.49249555e+12 1.54314166e+13]
 [1.59550640e+14 1.64964807e+15 1.70562698e+16 1.76350547e+17
  1.82334800e+18 1.88522122e+19 1.94919403e+20]
 [2.01533769e+21 2.08372585e+22 2.15443469e+23 2.22754295e+24
  2.30313206e+25 2.38128619e+26 2.46209240e+27]
 [2.54564067e+28 2.63202406e+29 2.72133877e+30 2.81368427e+31
  2.90916341e+32 3.00788252e+33 3.10995155e+34]
 [3.21548418e+35 3.32459793e+36 3.43741434e+37 3.55405904e+38
  3.67466194e+39 3.79935737e+40 3.92828419e+41]
 [4.06158599e+42 4.19941123e+43 4.34191342e+44 4.48925126e+45
  4.64158883e+46 4.79909581e+47 4.96194760e+48]
 [5.13032558e+49 5.30441728e+50 5.48441658e+51 5.67052394e+52
  5.86294665e+53 6.06189899e+54 6.26760256e+55]
 [6.48028644e+56 6.70018750e+57 6.92755066e+58 7.16262912e+59
  7.40568469e+60 7.65698808e+61 7.91681916e+62]
 [8.185467

In [ ]:
#ham random.rand()
a = np.random.rand(10,7)
print(a)
print("so chieu cua ma tran A: ",a.ndim)
print("so chieu cua ma tran chuyen vi A: ",a.T.ndim)
print("so kich thuoc cua ma tran A: ",a.shape)
print("so kich thuoc cua ma tran chuyen vi A: ",a.T.shape)

[[0.98740953 0.87447793 0.73467179 0.3382906  0.66282275 0.57066358
  0.89839512]
 [0.33089306 0.59368739 0.97914612 0.04574198 0.73788073 0.59255612
  0.88655438]
 [0.46331292 0.62182091 0.29383419 0.01283271 0.24305635 0.40276162
  0.50150864]
 [0.78144364 0.1484967  0.25585557 0.41411945 0.83516669 0.25587182
  0.20269876]
 [0.26020695 0.05546035 0.14032414 0.14649455 0.61083188 0.66312297
  0.62343466]
 [0.52507712 0.226851   0.39324424 0.35005806 0.53762588 0.33814414
  0.8075551 ]
 [0.29089733 0.74196086 0.79850487 0.81980804 0.84880796 0.60652226
  0.76973679]
 [0.57730816 0.72551115 0.89949383 0.39515186 0.75217534 0.69462737
  0.33770199]
 [0.79415672 0.56794106 0.69860579 0.81259792 0.59300803 0.91188297
  0.35739584]
 [0.48018014 0.39144706 0.27544866 0.44862229 0.52582607 0.17834108
  0.49109218]]
so chieu cua ma tran A:  2
so chieu cua ma tran chuyen vi A:  2
so kich thuoc cua ma tran A:  (10, 7)
so kich thuoc cua ma tran chuyen vi A:  (7, 10)


cau 3

In [ ]:
#chuyen ma tran o cau 2 thanh vector
a.flatten()

array([0.98740953, 0.87447793, 0.73467179, 0.3382906 , 0.66282275,
       0.57066358, 0.89839512, 0.33089306, 0.59368739, 0.97914612,
       0.04574198, 0.73788073, 0.59255612, 0.88655438, 0.46331292,
       0.62182091, 0.29383419, 0.01283271, 0.24305635, 0.40276162,
       0.50150864, 0.78144364, 0.1484967 , 0.25585557, 0.41411945,
       0.83516669, 0.25587182, 0.20269876, 0.26020695, 0.05546035,
       0.14032414, 0.14649455, 0.61083188, 0.66312297, 0.62343466,
       0.52507712, 0.226851  , 0.39324424, 0.35005806, 0.53762588,
       0.33814414, 0.8075551 , 0.29089733, 0.74196086, 0.79850487,
       0.81980804, 0.84880796, 0.60652226, 0.76973679, 0.57730816,
       0.72551115, 0.89949383, 0.39515186, 0.75217534, 0.69462737,
       0.33770199, 0.79415672, 0.56794106, 0.69860579, 0.81259792,
       0.59300803, 0.91188297, 0.35739584, 0.48018014, 0.39144706,
       0.27544866, 0.44862229, 0.52582607, 0.17834108, 0.49109218])

In [ ]:
#chuyen vector thanh ma tran
a.reshape(10,7)

array([[0.98740953, 0.87447793, 0.73467179, 0.3382906 , 0.66282275,
        0.57066358, 0.89839512],
       [0.33089306, 0.59368739, 0.97914612, 0.04574198, 0.73788073,
        0.59255612, 0.88655438],
       [0.46331292, 0.62182091, 0.29383419, 0.01283271, 0.24305635,
        0.40276162, 0.50150864],
       [0.78144364, 0.1484967 , 0.25585557, 0.41411945, 0.83516669,
        0.25587182, 0.20269876],
       [0.26020695, 0.05546035, 0.14032414, 0.14649455, 0.61083188,
        0.66312297, 0.62343466],
       [0.52507712, 0.226851  , 0.39324424, 0.35005806, 0.53762588,
        0.33814414, 0.8075551 ],
       [0.29089733, 0.74196086, 0.79850487, 0.81980804, 0.84880796,
        0.60652226, 0.76973679],
       [0.57730816, 0.72551115, 0.89949383, 0.39515186, 0.75217534,
        0.69462737, 0.33770199],
       [0.79415672, 0.56794106, 0.69860579, 0.81259792, 0.59300803,
        0.91188297, 0.35739584],
       [0.48018014, 0.39144706, 0.27544866, 0.44862229, 0.52582607,
        0.17834108, 0.4

cau 4 

In [34]:
import numpy as np
a = np.logspace(0,150,num=150).reshape(10,15)
print(a)
print("hang thu 3 cua ma tran a: ", a[2:3])
print("cot thu 5 cua ma tran a: ", a[:,4:5])


[[1.00000000e+000 1.01557362e+001 1.03138977e+002 1.04745224e+003
  1.06376485e+004 1.08033152e+005 1.09715619e+006 1.11424288e+007
  1.13159567e+008 1.14921870e+009 1.16711619e+010 1.18529241e+011
  1.20375170e+012 1.22249846e+013 1.24153719e+014]
 [1.26087241e+015 1.28050875e+016 1.30045090e+017 1.32070362e+018
  1.34127175e+019 1.36216020e+020 1.38337396e+021 1.40491810e+022
  1.42679775e+023 1.44901815e+024 1.47158460e+025 1.49450249e+026
  1.51777730e+027 1.54141458e+028 1.56541998e+029]
 [1.58979923e+030 1.61455815e+031 1.63970266e+032 1.66523876e+033
  1.69117254e+034 1.71751022e+035 1.74425806e+036 1.77142246e+037
  1.79900992e+038 1.82702700e+039 1.85548042e+040 1.88437696e+041
  1.91372352e+042 1.94352711e+043 1.97379486e+044]
 [2.00453398e+045 2.03575182e+046 2.06745584e+047 2.09965360e+048
  2.13235280e+049 2.16556124e+050 2.19928686e+051 2.23353771e+052
  2.26832196e+053 2.30364794e+054 2.33952406e+055 2.37595891e+056
  2.41296118e+057 2.45053971e+058 2.48870348e+059]
 [2.

cau 5

In [ ]:
import numpy as np

#Ham tinh gia tri trung binh: np.mean()
x = np.array([1,2,3,4,5])
print("tinh gia tri trung binh: ",np.mean(x))

#Ham tinh gia tri trung vi : np.median()
X = np.array([2, 5, 3, 4,1, 7])
print("tinh gia tri trung vi: ",np.median(X))

#Ham tinh gia tri yeu vi : np.nanmedian()
y = np.array([2, 5, 3, 4,1, 7,np.nan])
print("tinh gia tri yeu vi: ",np.nanmedian(y))

#Ham tinh phuong sai : np.var()
Y = np.array([1,2,4,6,7])
print("tinh phuong sai: ",np.var(Y))

#Ham tinh do lech chuan : np.std()
print("tinh do lech chuan: ", np.std(Y))

tinh gia tri trung binh:  3.0
tinh gia tri trung vi:  3.5
tinh gia tri yeu vi:  3.5
tinh phuong sai:  5.2
tinh do lech chuan:  2.280350850198276


In [35]:
#GT trung binh
import numpy as np
a = np.arange(1,151).reshape(15,10)
print(a)
print("gia tri trung binh tung hang cua ma tran a: ",np.mean(a,axis=1))
print("gia tri trung binh tung cot cua ma tran a: ",np.mean(a,axis=0))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]
gia tri trung binh tung hang cua ma tran a:  [  5.5  15.5  25.5  35.5  45.5  55.5  65.5  75.5  85.5  95.5 105.5 115.5
 125.5 135.5 145.5]
gia tri trung binh tung cot cua ma tran a:  [71. 72. 73. 74. 75. 76. 77. 78. 79. 80.]


In [37]:
#GT trung vi
a = np.arange(1,151).reshape(15,10)
print(a)
print("gia tri trung vi tung hang cua ma tran a: ",np.median(a,axis=1))
print("gia tri trung binh tung cot cua ma tran a: ",np.median(a,axis =0))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]
gia tri trung vi tung hang cua ma tran a:  [  5.5  15.5  25.5  35.5  45.5  55.5  65.5  75.5  85.5  95.5 105.5 115.5
 125.5 135.5 145.5]
gia tri trung binh tung cot cua ma tran a:  [71. 72. 73. 74. 75. 76. 77. 78. 79. 80.]


In [38]:
#GT phuong sai
a = np.arange(1,151).reshape(15,10)
print(a)
print("phuong sai tung hang cua ma tran a: ",np.var(a,axis=1))
print("phuong sai tung cot cua ma tran a: ",np.var(a,axis =0))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]
phuong sai tung hang cua ma tran a:  [8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25
 8.25]
phuong sai tung cot cua ma tran a:  [1866.66666667 1866.66666667 1866.66666667 1866.66666667 1866.66666667
 1866.66666667 1866.66666667 1866.66666667 1866.66666667 1866.66666667]


In [39]:
#GT do lech chuan
a = np.arange(1,151).reshape(15,10)
print(a)
print("do lech chuan tung hang cua ma tran a: ",np.std(a,axis=1))
print("do lech chuan tung cot cua ma tran a: ",np.std(a,axis =0))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]
do lech chuan tung hang cua ma tran a:  [2.87228132 2.87228132 2.87228132 2.87228132 2.87228132 2.87228132
 2.87228132 2.87228132 2.87228132 2.87228132 2.87228132 2.87228132
 2.87228132 2.87228132 2.87228132]
do lech chuan tung cot cua ma tran a:  [43.20493799 43.20493799 43.20493799 43.20493799 43.20493799 43.20493799
 43.20493799 43.20493799 43.20493