<a href="https://colab.research.google.com/github/lenaphamthi/bai_tap_numpy/blob/main/bai_tap_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: Xét không gian R3 , một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo ggiá trị của điểm A nêu trên bằng Numpy.

In [ ]:
import numpy as np
A = np.array([5,7,14 ])
A 

array([ 5,  7, 14])

Bài 2: Mở rộng không gian lên R15, điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7,
8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong không gian 15 chiều này bằng Numpy.

In [ ]:
A = np.arange(1,16)
A 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Bài 3

In [ ]:
x = int(input("nhap so nguyen: "))
y = np.random.rand(1,x)
y



nhap so nguyen: 5


array([[0.10074601, 0.44172434, 0.24222569, 0.66541187, 0.41046082]])

bai 4 

In [ ]:
A = np.array([7,-5,8])
print("chiều dài vector OA: ",np.linalg.norm(A))

chiều dài vector OA:  11.74734012447073


bai 5

In [ ]:
A = np.random.rand(1,3)
B = np.random.rand(2,3)
print("chiều dài của vector A,B:",np.linalg.norm(A-B))

chiều dài của vector A,B: 1.3086615555020038


bai 6 

In [ ]:
n = int(input("nhap vao so nguyen duong: "))
a = np.random.rand(n)
b = np.random.rand(n)
print("tích vô hướng của 2 vector a,b: ",np.inner(a,b))


nhap vao so nguyen duong: 4
tích vô hướng của 2 vector a,b:  1.3386916041930421


In [ ]:
import numpy as np


bai 7 

In [ ]:
n = int(input("nhap vao so nguyen duong: "))
a = np.random.rand(n)
b = np.random.rand(n)
print("tích hữu hướng: ",np.cross(a,b))

nhap vao so nguyen duong: 2
tích hữu hướng:  -0.17390601513964116


bai 8 

In [ ]:
import numpy as np 
n = int(input("nhập vào số nguyên: "))
a = np.random.rand(1,n)
a
a.T

nhập vào số nguyên: 4


array([[0.35534242],
       [0.05084234],
       [0.55920421],
       [0.7836748 ]])

bai 9

In [ ]:
a = [1,2,3,4,5]
b = [[1],[2],[3],[4],[5]]
print ("a: ",a)
print ("b: ",b)
a = np.array([1,2,3,4,5])
b = np.array([[1],[2],[3],[4],[5]])
print ("vector a: ",a)
print ("vector b: ",b)
print("chuyển vị vector a: ",a.T)
print ("chuyển vị vector b: ",b.T)

a:  [1, 2, 3, 4, 5]
b:  [[1], [2], [3], [4], [5]]
vector a:  [1 2 3 4 5]
vector b:  [[1]
 [2]
 [3]
 [4]
 [5]]
chuyển vị vector a:  [1 2 3 4 5]
chuyển vị vector b:  [[1 2 3 4 5]]


bai 10

In [ ]:
n = int(input("nhập vào số nguyên: "))
a = np.random.rand(n)
b = np.random.rand(n)
m = int(input("nhap vao so bat ky: "))
print("thực hiện phép nhân: ",m*a)
print("thực hiện phép cộng 2 vector: ",a+b)

nhập vào số nguyên: 2
nhap vao so bat ky: 3
thực hiện phép nhân:  [2.32663515 1.63045238]
thực hiện phép cộng 2 vector:  [0.85402752 1.48523983]
