<a href="https://colab.research.google.com/github/lenaphamthi/bai_tap_numpy/blob/main/bai_tap_numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm này.



numpy. apply_along_axis ( func1d , axis , arr , * args , ** kwargs )
+ hàm func1d (M,) -> (Nj…) : Hàm này phải chấp nhận mảng 1-D. Nó được áp dụng cho các lát arr 1-D dọc theo trục được chỉ định.
+ axis : số nguyên trục

Trục dọc theo arr được cắt.

+ arr :ndarray (Ni…, M, Nk…)

Đầu vào mảng.

+ args: bất kỳ

Đối số bổ sung cho func1d .

+ kwargs: bất kỳ

câu 2 : Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [2]:
import numpy as np

In [4]:

a = np.random.randint(1,10,[15,17])
a

array([[8, 6, 1, 2, 4, 7, 5, 4, 2, 6, 8, 8, 9, 1, 3, 6, 8],
       [6, 1, 1, 2, 6, 8, 3, 6, 7, 6, 9, 8, 3, 9, 1, 8, 8],
       [3, 8, 7, 7, 6, 9, 6, 2, 7, 7, 5, 7, 8, 9, 5, 9, 6],
       [2, 1, 2, 2, 9, 1, 8, 1, 8, 3, 1, 3, 9, 1, 7, 1, 5],
       [9, 2, 4, 2, 5, 2, 4, 3, 5, 1, 6, 6, 1, 3, 5, 2, 3],
       [9, 3, 6, 1, 4, 7, 8, 9, 6, 8, 4, 1, 5, 2, 1, 6, 8],
       [9, 1, 8, 7, 6, 9, 7, 8, 1, 9, 3, 6, 5, 5, 1, 2, 8],
       [3, 8, 1, 3, 6, 6, 7, 1, 9, 5, 9, 1, 8, 9, 3, 7, 7],
       [4, 9, 1, 1, 4, 4, 7, 3, 1, 6, 6, 8, 3, 1, 5, 3, 9],
       [4, 6, 5, 8, 3, 6, 8, 4, 3, 9, 1, 4, 4, 8, 4, 8, 7],
       [7, 9, 8, 3, 8, 4, 5, 1, 6, 3, 1, 6, 6, 2, 8, 3, 5],
       [8, 7, 6, 6, 8, 7, 3, 1, 7, 9, 3, 3, 8, 7, 1, 1, 1],
       [8, 1, 7, 7, 9, 8, 5, 8, 9, 4, 8, 7, 1, 4, 2, 6, 3],
       [8, 1, 4, 2, 2, 6, 7, 7, 3, 3, 5, 1, 5, 7, 8, 4, 2],
       [8, 1, 1, 1, 5, 9, 6, 3, 8, 8, 7, 3, 7, 7, 6, 2, 7]])

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tim_gia_tri_lon_nhat(a):
 return np.max(a)
np.apply_along_axis(tim_gia_tri_lon_nhat,1,a)

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 9, 7, 9, 9])

Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tim_gia_tri_nho_nhat(a):
  return np.min(a)
np.apply_along_axis(tim_gia_tri_nho_nhat,0,a)

array([2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1])

Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [7]:
def tinh_tong(a):
  return np.sum(a)
print(" tổng các phần tử của vector")
print(np.apply_along_axis(tinh_tong,1,a))

 tổng các phần tử của vector
[ 88  92 111  64  63  88  95  93  75  92  85  86  97  75  89]


Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [6]:
def tinh_tong_2(vector_a):
  sum  = 0
  for i in range(len(vector_a)):
    if (i % 2 != 0):
      sum  = sum +vector_a[i]
  return sum
print("tổng các phần tử có chỉ số lẻ")
print (np.apply_along_axis(tinh_tong_2, 1, a))

tổng các phần tử có chỉ số lẻ
[40 48 58 13 21 37 47 40 35 53 31 41 45 31 34]
